AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Style/OpenStructUse:
  Enabled: false
